"""
Prompt definitions for DINO detection, SAM refinement, and CLIP evaluation.
Each prompt includes all necessary settings for the detection and evaluation pipeline.
Add new prompts here as you discover them.
"""

# All available prompt definitions
AVAILABLE_PROMPTS = {
    "sitting_area": {
        # Proxy label for areas likely suitable for sitting or lingering.
        "caption": "plaza . courtyard . outdoor seating . patio . bench . picnic table . park . tree-lined lawn . public square",
        "negative_dino_caption": "building . roof . parking lot . road . car . highway . construction site . empty field",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.30,
        "box_threshold": 0.24,
        "text_threshold": 0.20,
        "keywords": ("plaza", "courtyard", "seating", "bench", "table", "patio", "park", "square"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "highway", "construction"),
        "min_aspect_ratio": 0.6,
        "max_aspect_ratio": 12.0,
        "min_box_side_px": 24,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 120000,
        "negative_captions": ["building roof", "parking lot", "road", "highway"],
        "clip_negative_weight": 0.40,
        "clip_top_k": 50,
        "clip_score_threshold": 0.02,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.60,
        "max_saturation": 1.0,
        "min_value": 0.18,
    },
    "walking_area": {
        # Proxy label for walkable pedestrian corridors and sidewalks.
        "caption": "sidewalk . pedestrian walkway . footpath . paved walkway . pedestrian path . trail . promenade",
        "negative_dino_caption": "building . roof . parking lot . road . highway . car . construction site . empty field",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.28,
        "box_threshold": 0.18,
        "text_threshold": 0.14,
        "keywords": ("sidewalk", "walkway", "footpath", "path", "trail", "promenade", "pedestrian"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "highway", "construction"),
        "min_aspect_ratio": 0.4,
        "max_aspect_ratio": 24.0,
        "min_box_side_px": 18,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 150000,
        "negative_captions": ["building roof", "parking lot", "road lane", "highway"],
        "clip_negative_weight": 0.42,
        "clip_top_k": 50,
        "clip_score_threshold": 0.0,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.00015,
        "clip_max_area_ratio": 0.65,
        "max_saturation": 1.0,
        "min_value": 0.18,
    },
    "uncomfortable_area": {
        # Proxy label for exposed, hardscape-heavy, lower-comfort areas.
        "caption": "road . parking lot . asphalt . concrete plaza . exposed hardscape . highway . vacant lot . building roof",
        "negative_dino_caption": "park . tree canopy . grass lawn . outdoor seating . plaza . courtyard",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.30,
        "box_threshold": 0.18,
        "text_threshold": 0.14,
        "keywords": ("road", "parking", "asphalt", "concrete", "hardscape", "highway", "vacant", "roof"),
        "negative_keywords": ("park", "tree", "grass", "seating", "plaza", "courtyard"),
        "min_aspect_ratio": 0.35,
        "max_aspect_ratio": 30.0,
        "min_box_side_px": 20,
        "max_split_boxes_per_detection": 128,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 250000,
        "negative_captions": ["park", "tree canopy", "grass lawn", "outdoor seating"],
        "clip_negative_weight": 0.45,
        "clip_top_k": 60,
        "clip_score_threshold": -0.02,
        "clip_relative_score_margin": 0.12,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.85,
        "max_saturation": 1.0,
        "min_value": 0.12,
    },
    "sports_court": {
        # Sports courts and athletic areas - HIGHEST PRIORITY (most specific, very reliable)
        "caption": "basketball court . tennis court . sports court . hard court . fenced court",
        "negative_dino_caption": "building . roof . parking lot . road",
        "negative_box_threshold": 0.35,
        "negative_text_threshold": 0.30,
        # DINO detection settings
        "box_threshold": 0.17,
        "text_threshold": 0.12,
        "keywords": ("court", "sports", "basketball", "tennis", "athletic", "playground"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "grass", "tree"),
        "min_aspect_ratio": 0.6,  # Courts are somewhat rectangular
        "max_aspect_ratio": 3.0,   # But not too elongated
        "min_box_side_px": 30,     # Courts are substantial size
        "max_split_boxes_per_detection": 64,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 50000,
        "negative_captions": ["building", "roof", "parking lot", "road"],
        "clip_negative_weight": 0.38,
        # SAM/CLIP evaluation settings
        "clip_top_k": 20,
        "clip_score_threshold": 0.12,
        "clip_relative_score_margin": 0.08,
        "clip_min_area_ratio": 0.0005,
        "clip_max_area_ratio": 0.20,
        "max_saturation": 1.0,
        "min_value": 0.20,
    },
    "gathering_space": {
        # Combined detector for outdoor gathering areas: both seated (outdoor_seating) and standing (plaza/courtyard)
        # Detects plazas, courtyards, patios, terraces, and open social gathering areas
        "caption": "plaza . courtyard . outdoor gathering area . public square . terrace . outdoor seating . patio . bench . picnic table . pedestrian area . open congregation area",
        "negative_dino_caption": "building . roof . parking lot . road . car . highway . construction site . grass field . empty field",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.30,
        # DINO detection settings - tuned to catch both seated and standing gathering types
        "box_threshold": 0.28,  # Slightly lower to catch both types
        "text_threshold": 0.24,  # Slightly lower for better recall
        "keywords": ("plaza", "courtyard", "gathering", "square", "terrace", "bench", "table", "seating", "patio", "dining", "pedestrian"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "highway", "construction", "grass", "field"),
        "min_aspect_ratio": 0.7,  # Can be varied aspect ratios (squares or rectangles)
        "max_aspect_ratio": 9.0,  # Gathering areas can be somewhat elongated
        "min_box_side_px": 25,  # Gathering spaces are substantial
        "max_split_boxes_per_detection": 72,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 60000,  # Courtyards/plazas can be large
        "negative_captions": [
            "building roof",
            "parking lot",
            "sports field",
            "tree canopy",
            "grass lawn",
        ],
        "clip_negative_weight": 0.43,  # Strong rejection of empty/barren areas
        # SAM/CLIP evaluation settings
        "clip_top_k": 50,
        "clip_score_threshold": 0.03,  # Moderate threshold for gathering areas
        "clip_relative_score_margin": 0.14,
        "clip_min_area_ratio": 0.0003,
        "clip_max_area_ratio": 0.45,
        "max_saturation": 1.0,  # Varied saturation (furniture, people, pavement)
        "min_value": 0.22,  # Can be in partial shade
    },
    "seated_dining": {
        # Actual prompts given to DINO/SAM - specific to outdoor restaurants/cafes
        "caption": "outdoor cafe . restaurant patio . dining tables . outdoor seating with tables . alfresco dining",
        # DINO detection settings
        "box_threshold": 0.26,
        "text_threshold": 0.24,
        "keywords": ("dining", "cafe", "restaurant", "table", "seating", "patio"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "highway", "grass", "field"),
        "min_aspect_ratio": 0.9,
        "max_aspect_ratio": 7.0,
        "min_box_side_px": 20,
        "max_split_boxes_per_detection": 48,
        "enable_area_split": False,
        "enable_tiled_fallback": False,
        "max_area_meters_sq": 20000,  # Cafe areas are typically smaller than plazas
        "negative_captions": [
            "parking lot",
            "highway",
            "empty street",
            "grass field",
            "roof",
        ],
        "clip_negative_weight": 0.40,
        # SAM/CLIP evaluation settings
        "clip_top_k": 45,
        "clip_score_threshold": 0.10,  # Dining areas should have strong positive signal
        "clip_relative_score_margin": 0.12,
        "clip_min_area_ratio": 0.0003,
        "clip_max_area_ratio": 0.30,
        "max_saturation": 1.0,
        "min_value": 0.30,
    },
    "standing_gathering": {
        # Actual prompts given to DINO/SAM - plazas, courtyards, open gathering spaces
        "caption": "plaza . courtyard . outdoor gathering area . public square . terrace . open congregation area",
        "negative_dino_caption": "building . roof . parking lot . road . car . highway . construction site . grass field . empty field",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.30,
        # DINO detection settings
        "box_threshold": 0.29,
        "text_threshold": 0.25,
        "keywords": ("plaza", "courtyard", "gathering", "square", "terrace"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "highway", "construction", "grass", "field"),
        "min_aspect_ratio": 0.7,
        "max_aspect_ratio": 9.0,
        "min_box_side_px": 30,
        "max_split_boxes_per_detection": 72,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 60000,  # Plazas can be quite large
        "negative_captions": [
            "building roof",
            "parking lot",
            "sports field",
            "tree canopy",
            "grass lawn",
        ],
        "clip_negative_weight": 0.42,
        # SAM/CLIP evaluation settings
        "clip_top_k": 50,
        "clip_score_threshold": 0.02,
        "clip_relative_score_margin": 0.14,
        "clip_min_area_ratio": 0.0004,
        "clip_max_area_ratio": 0.50,
        "max_saturation": 1.0,
        "min_value": 0.20,  # Plazas may have shadows
    },
    "park": {
        # Parks and green public open spaces
        "caption": "park . city park . public park . urban park . green space . playground . parkland . tree-lined park . grassy park . lawn",
        "negative_dino_caption": "building . roof . parking lot . road . highway . car . tree canopy . deep shadow",
        "negative_box_threshold": 0.35,
        "negative_text_threshold": 0.28,
        # DINO detection settings
        "box_threshold": 0.10,
        "text_threshold": 0.12,
        "keywords": ("park", "green", "lawn", "playground", "trees", "garden", "field"),
        "negative_keywords": ("building", "roof", "parking", "road", "car", "highway", "shadow", "canopy"),
        "min_aspect_ratio": 0.5,
        "max_aspect_ratio": 12.0,
        "min_box_side_px": 25,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "refine_bounds": False,
        "prefer_smaller_boxes": False,
        "max_area_meters_sq": 150000,
        "negative_captions": [
            "building",
            "roof",
            "parking lot",
            "road",
            "highway",
            "tree canopy",
            "deep shadow",
        ],
        "clip_negative_weight": 0.35,
        # SAM/CLIP evaluation settings
        "clip_top_k": 50,
        "clip_score_threshold": 0.00,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.60,
        "max_saturation": 1.0,
        "min_value": 0.18,
    },
    "transit_hub": {
        # Transit-adjacent gathering points.
        "caption": "bus stop . subway entrance . metro entrance . train station entrance . bike rack . transit shelter",
        "negative_dino_caption": "building roof . parking lot . road lane . highway",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.28,
        "box_threshold": 0.18,
        "text_threshold": 0.14,
        "keywords": ("bus", "subway", "metro", "station", "bike", "rack", "transit", "shelter", "entrance"),
        "negative_keywords": ("roof", "building", "highway", "parking"),
        "min_aspect_ratio": 0.25,
        "max_aspect_ratio": 12.0,
        "min_box_side_px": 14,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 35000,
        "negative_captions": [
            "building roof",
            "parking lot",
            "highway",
            "empty grass field",
        ],
        "clip_negative_weight": 0.40,
        "clip_top_k": 45,
        "clip_score_threshold": 0.02,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.00005,
        "clip_max_area_ratio": 0.25,
        "max_saturation": 1.0,
        "min_value": 0.16,
    },
    "pedestrian_features": {
        # Pedestrian-centric public features often correlated with gathering.
        "caption": "crosswalk . playground . gazebo . amphitheater . pedestrian plaza . public square",
        "negative_dino_caption": "building roof . highway . parking lot . industrial lot",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.28,
        "box_threshold": 0.16,
        "text_threshold": 0.13,
        "keywords": ("crosswalk", "playground", "gazebo", "amphitheater", "pedestrian", "plaza", "square"),
        "negative_keywords": ("roof", "building", "highway", "industrial", "warehouse"),
        "min_aspect_ratio": 0.25,
        "max_aspect_ratio": 14.0,
        "min_box_side_px": 16,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 90000,
        "negative_captions": [
            "building roof",
            "industrial roof",
            "highway",
            "parking lot",
        ],
        "clip_negative_weight": 0.42,
        "clip_top_k": 50,
        "clip_score_threshold": 0.00,
        "clip_relative_score_margin": 0.12,
        "clip_min_area_ratio": 0.00008,
        "clip_max_area_ratio": 0.40,
        "max_saturation": 1.0,
        "min_value": 0.18,
    },
    "furniture": {
        # Optional prompt kept for future high-resolution imagery; usually too small at campus-scale satellite GSD.
        "caption": "table . chair . bench . umbrella . outdoor furniture",
        # DINO detection settings
        "box_threshold": 0.22,
        "text_threshold": 0.20,
        "keywords": ("table", "chair", "bench", "umbrella", "furniture", "picnic"),
        "negative_keywords": ("building", "roof", "parking", "road", "highway", "grass", "field"),
        "min_aspect_ratio": 0.6,
        "max_aspect_ratio": 6.0,
        "min_box_side_px": 15,
        "max_split_boxes_per_detection": 128,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 5000,  # Individual furniture items
        "negative_captions": [
            "building roof",
            "asphalt",
            "street",
            "parking",
        ],
        "clip_negative_weight": 0.35,
        # SAM/CLIP evaluation settings
        "clip_top_k": 40,
        "clip_score_threshold": 0.0,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.00001,
        "clip_max_area_ratio": 0.08,
        "max_saturation": 1.0,
        "min_value": 0.15,
    },
    "building_roof": {
        # Building roof detection - easy to identify for model testing
        "caption": "building . roof . apartment building . brownstone . skyscraper . office building . residential building",
        # DINO detection settings - RELAXED for testing
        "box_threshold": 0.08,  # Low threshold to catch more roof candidates
        "text_threshold": 0.05,  # Low text threshold for better recall
        "keywords": ("roof", "building", "top"),
        "negative_keywords": ("car", "truck", "person", "tree", "grass"),
        "min_aspect_ratio": 0.3,  # Relaxed to catch angled buildings
        "max_aspect_ratio": 25.0,  # Increased significantly for rotated buildings appearing as elongated boxes
        "min_box_side_px": 8,  # Reduced to catch smaller buildings
        "max_split_boxes_per_detection": 256,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 1000000,  # Buildings can be large
        "negative_captions": [
            "parking lot",
            "road",
            "grass",
        ],
        "clip_negative_weight": 0.30,
        # SAM/CLIP evaluation settings
        "clip_top_k": 50,
        "clip_score_threshold": -0.15,  # More aggressive - lower threshold to catch more buildings
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.0001,
        "clip_max_area_ratio": 0.90,  # Can be large
        "max_saturation": 1.0,
        "min_value": 0.10,  # Roofs can be dark
    },
    "warehouse_roof": {
        # Large industrial/commercial roofs, kept separate for shape-specific tuning.
        "caption": "warehouse . warehouse roof . industrial building . factory roof . distribution center . logistics building",
        "box_threshold": 0.10,
        "text_threshold": 0.06,
        "keywords": ("warehouse", "industrial", "factory", "distribution", "logistics", "roof", "building"),
        "negative_keywords": ("car", "truck", "person", "tree", "grass"),
        "min_aspect_ratio": 0.15,
        "max_aspect_ratio": 40.0,
        "min_box_side_px": 16,
        "max_split_boxes_per_detection": 256,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 1500000,
        "negative_captions": [
            "parking lot",
            "road",
            "grass",
            "sports court",
        ],
        "clip_negative_weight": 0.32,
        "clip_top_k": 50,
        "clip_score_threshold": -0.10,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.95,
        "max_saturation": 1.0,
        "min_value": 0.08,
    },
    "sidewalk_surface": {
        # Sidewalks/walkways with explicit paved-surface semantics.
        "caption": "sidewalk . pedestrian sidewalk . concrete sidewalk . paved walkway . footpath . concrete path . asphalt walkway",
        "negative_dino_caption": "building roof . parking lot . highway lane . roadway",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.28,
        # DINO detection settings
        "box_threshold": 0.18,
        "text_threshold": 0.14,
        "keywords": ("sidewalk", "pedestrian", "walkway", "footpath", "pavement", "concrete", "asphalt"),
        "negative_keywords": ("building", "roof", "car", "highway", "parking", "grass", "field", "roadway"),
        "min_aspect_ratio": 0.6,
        "max_aspect_ratio": 20.0,  # Paths can be very elongated
        "min_box_side_px": 18,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 120000,
        "negative_captions": [
            "building roof",
            "parking lot",
            "highway",
            "road lane",
            "tree canopy",
        ],
        "clip_negative_weight": 0.42,
        # SAM/CLIP evaluation settings
        "clip_top_k": 50,
        "clip_score_threshold": 0.0,
        "clip_relative_score_margin": 0.12,
        "clip_min_area_ratio": 0.00015,
        "clip_max_area_ratio": 0.45,
        "max_saturation": 1.0,
        "min_value": 0.18,
    },
    "road_surface": {
        # Roads/streets with explicit asphalt-vs-concrete phrasing for CLIP confirmation.
        "caption": "road . asphalt road . concrete road . street . roadway . traffic lane . paved road",
        "negative_dino_caption": "building roof . parking lot . sidewalk . pedestrian walkway",
        "negative_box_threshold": 0.34,
        "negative_text_threshold": 0.28,
        # DINO detection settings
        "box_threshold": 0.16,
        "text_threshold": 0.12,
        "keywords": ("road", "street", "lane", "roadway", "asphalt", "concrete", "paved"),
        "negative_keywords": ("building", "roof", "parking", "grass", "field", "sidewalk", "walkway"),
        "min_aspect_ratio": 0.35,
        "max_aspect_ratio": 40.0,
        "min_box_side_px": 20,
        "max_split_boxes_per_detection": 120,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 300000,
        "negative_captions": [
            "building roof",
            "parking lot",
            "sidewalk",
            "pedestrian path",
            "tree canopy",
        ],
        "clip_negative_weight": 0.44,
        # SAM/CLIP evaluation settings
        "clip_top_k": 60,
        "clip_score_threshold": -0.02,
        "clip_relative_score_margin": 0.12,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.80,
        "max_saturation": 1.0,
        "min_value": 0.16,
    },
    "sidewalks": {
        # Backward-compatible alias settings (kept for old configs/scripts).
        "caption": "sidewalk . pedestrian path . walkway . footpath . pavement . concrete path . pedestrian sidewalk",
        "box_threshold": 0.20,
        "text_threshold": 0.15,
        "keywords": ("sidewalk", "pedestrian", "walkway", "footpath", "pavement", "path"),
        "negative_keywords": ("building", "roof", "car", "road", "highway", "parking", "grass", "field"),
        "min_aspect_ratio": 0.6,
        "max_aspect_ratio": 15.0,
        "min_box_side_px": 20,
        "max_split_boxes_per_detection": 96,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 100000,
        "negative_captions": ["parking lot", "highway", "grass field", "tree canopy"],
        "clip_negative_weight": 0.40,
        "clip_top_k": 50,
        "clip_score_threshold": 0.0,
        "clip_relative_score_margin": 0.12,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.35,
        "max_saturation": 1.0,
        "min_value": 0.20,
    },
    # NEN 8100 Wind Comfort Categories (A-E) using environmental proxy descriptors
    # These prompts use keywords that DINO can detect to classify areas by wind comfort suitability
    "nen_cat_a": {
        # Combined Category A/B: sheltered, vegetated, comfortable outdoor areas for sitting and lingering.
        # NOW MORE LENIENT: captures any park, green space, plaza, seating area, or well-maintained outdoor gathering area
        "caption": "park . green space . plaza . outdoor seating . public square . vegetated area . trees . outdoor gathering . courtyard . patio . cafe . restaurant . bench . public space . landscaped area . public garden",
        "negative_dino_caption": "highway . parking lot . major road . freeway",
        "box_threshold": 0.15,
        "text_threshold": 0.12,
        "keywords": ("park", "green", "plaza", "seating", "trees", "shade", "outdoor", "gathering", "courtyard", "garden", "public", "patio", "cafe"),
        "negative_keywords": ("parking", "highway", "freeway", "major road"),
        "min_aspect_ratio": 0.4,
        "max_aspect_ratio": 20.0,
        "min_box_side_px": 20,
        "max_split_boxes_per_detection": 128,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 200000,
        "negative_captions": ["highway", "freeway", "parking lot", "major road"],
        "clip_negative_weight": 0.25,
        "clip_top_k": 60,
        "clip_score_threshold": -0.15,
        "clip_relative_score_margin": 0.08,
        "clip_min_area_ratio": 0.0001,
        "clip_max_area_ratio": 0.80,
        "max_saturation": 1.0,
        "min_value": 0.15,
    },
    "nen_cat_b": {
        # Category B (2.5-5%): "Good – acceptable for strolling, short sitting"
        # Proxy: pedestrian-friendly areas with some seating and vegetation
        "caption": "pedestrians. pedestrian path . outdoor area with trees and benches . walkable plaza . gathering area with vegetation . public square with shade . park-like setting",
        "negative_dino_caption": "parking lot . highway . empty field . rooftop . construction . bare hardscape . windswept open area",
        "box_threshold": 0.24,
        "text_threshold": 0.20,
        "keywords": ("pedestrian", "seating", "trees", "plaza", "walkable", "gathering", "vegetation", "benches", "square"),
        "negative_keywords": ("parking", "highway", "empty", "rooftop", "construction", "bare", "windswept"),
        "min_aspect_ratio": 0.5,
        "max_aspect_ratio": 12.0,
        "min_box_side_px": 26,
        "max_split_boxes_per_detection": 90,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 100000,
        "negative_captions": ["parking lot", "highway", "empty field", "rooftop", "bare pavement"],
        "clip_negative_weight": 0.36,
        "clip_top_k": 50,
        "clip_score_threshold": 0.0,
        "clip_relative_score_margin": 0.11,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.45,
        "max_saturation": 1.0,
        "min_value": 0.18,
    },
    "nen_cat_c": {
        # Combined Category C/D: pedestrian-accessible outdoor spaces - open paved areas, walking zones, transitional areas.
        # NOW MORE LENIENT: captures any accessible outdoor area including hardscape, open plazas, walkways, paved surfaces
        "caption": "pedestrian area . walkway . paved area . open space . plaza . public path . outdoor area . sidewalk . accessible space . courtyard . outdoor plaza . paved plaza . public space . accessible outdoor . hardscape",
        "negative_dino_caption": "highway . freeway . parking lot . major road . rooftop . roof",
        "box_threshold": 0.13,
        "text_threshold": 0.10,
        "keywords": ("pedestrian", "walkway", "paved", "open", "plaza", "path", "accessible", "outdoor", "sidewalk", "courtyard", "space"),
        "negative_keywords": ("highway", "freeway", "parking", "major road", "roof", "rooftop"),
        "min_aspect_ratio": 0.3,
        "max_aspect_ratio": 30.0,
        "min_box_side_px": 18,
        "max_split_boxes_per_detection": 150,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 250000,
        "negative_captions": ["highway", "freeway", "parking lot", "major road", "rooftop"],
        "clip_negative_weight": 0.20,
        "clip_top_k": 70,
        "clip_score_threshold": -0.25,
        "clip_relative_score_margin": 0.05,
        "clip_min_area_ratio": 0.00008,
        "clip_max_area_ratio": 0.85,
        "max_saturation": 1.0,
        "min_value": 0.12,
    },
    "nen_cat_d": {
        # Category D has been merged into Category C.
        "caption": "exposed open area . windy plaza . minimally vegetated outdoor space . sparse pedestrian zone . exposed pavement area . windswept open plaza . minimal shelter area",
        "negative_dino_caption": "dense trees . sheltered plaza . park seating . outdoor cafe . covered area . building shelter . heavily vegetated",
        "box_threshold": 0.20,
        "text_threshold": 0.16,
        "keywords": ("exposed", "open", "windswept", "minimal", "sparse", "area", "pavement", "plaza"),
        "negative_keywords": ("trees", "sheltered", "seating", "cafe", "covered", "building", "vegetated", "dense"),
        "min_aspect_ratio": 0.4,
        "max_aspect_ratio": 20.0,
        "min_box_side_px": 22,
        "max_split_boxes_per_detection": 110,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 150000,
        "negative_captions": ["sheltered plaza", "park", "seating", "outdoor cafe", "covered area", "vegetation"],
        "clip_negative_weight": 0.40,
        "clip_top_k": 50,
        "clip_score_threshold": -0.08,
        "clip_relative_score_margin": 0.10,
        "clip_min_area_ratio": 0.0002,
        "clip_max_area_ratio": 0.65,
        "max_saturation": 1.0,
        "min_value": 0.15,
    },
    "nen_cat_e": {
        # Category E: highways, roofs, parking areas, and other inaccessible/no-access infrastructure and hardscape.
        # Captures major roads, freeways, rooftops, parking structures, service areas, industrial hardscape
        "caption": "highway . freeway . major road . rooftop . roof . parking . parking lot . parking structure . service road . industrial . infrastructure . building . large road . service area",
        "negative_dino_caption": "",
        "box_threshold": 0.12,
        "text_threshold": 0.09,
        "keywords": ("highway", "freeway", "road", "roof", "rooftop", "parking", "service", "infrastructure", "industrial", "building"),
        "negative_keywords": (),
        "min_aspect_ratio": 0.3,
        "max_aspect_ratio": 35.0,
        "min_box_side_px": 16,
        "max_split_boxes_per_detection": 160,
        "enable_area_split": False,
        "enable_tiled_fallback": True,
        "max_area_meters_sq": 300000,
        "negative_captions": [],
        "clip_negative_weight": 0.15,
        "clip_top_k": 80,
        "clip_score_threshold": -0.30,
        "clip_relative_score_margin": 0.05,
        "clip_min_area_ratio": 0.00005,
        "clip_max_area_ratio": 0.90,
        "max_saturation": 1.0,
        "min_value": 0.10,
    },
}
